### ISSUE TITLE
doT is missing

### ISSUE THREAD

**Issue by kahurangitama** [OmarElGabry/Hashtegny#4]
Hi! This is an awesome project! However when I try to npm install I got something like that:

```
npm WARN install Couldn't install optional dependency: Registry returned 404 for GET on https://registry.npmjs.org/doT
```

Is this critical? Will plugin work without this dependency? Any suggestion what can I use instead doT?

**Comment by OmarElgabry** [comment]
Thanks for reporting. It should be fixed now.

**Comment by yves-s** [comment]
Unfortunately the issue still exists.

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/yves.schleich/.nvm/versions/node/v6.1.0/bin/node" "/Users/yves.schleich/.nvm/versions/node/v6.1.0/bin/npm" "install" "hashtegny"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/doT
npm ERR! 404 
npm ERR! 404  'doT' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 It was specified as a dependency of 'hashtegny'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by OmarElgabry** [comment]
Your log shows that you're still using 'doT' instead of 'dot' in _package.json_ file, which is not valid name for the package. Please make sure you're using 'dot' and **not** 'doT'.

**Comment by yves-s** [comment]
Uh yes, sorry. In your package json the "dot" dependency is correctly set to `"dot": "~1.0.1"`.
But why does `npm install hashtegny` wants to install "doT", instead of "dot" from your package json? I don't get it. Shouldn't `npm install` install the packages dependency, in this case:
```
{
    "jquery": "~2.1.4",
    "codebird": "~2.6.0",
    "dot": "~1.0.1",
    "masonry-layout": "~3.3.2"
  }
```
or am I getting something wrong?

**Comment by OmarElgabry** [comment]
It should be working now. I've updated the package on npm. I needed to release a new version and publish it to the npm in order for the changes to take place on the npm registry.
