### ISSUE TITLE
how to show the instagram post?

### ISSUE THREAD

**Issue by galihpbu** [OmarElGabry/Hashtegny#6]
i cant show the instagram post, any way to show it? thanks

**Comment by OmarElgabry** [comment]
The New Instagram API doesn't provide access to public content using hashtags. I will try to fix it if possible, otherwise, unfortunately Instagram feeds won't be shown. You can check the documentation [here](https://www.instagram.com/developer/changelog/).

**Comment by OmarElgabry** [comment]
Instagram is working now as prior e3b6a401856bd1d952bddeae85607caa2c3a7997 commit. It's done by using an access token which has public_content scope approved, which in turn allows to get posts based on hashtag.
